### PR TITLE
Update to Chart.js v4, add version badges

### PR DESCRIPTION
**Pull request by igorlukanin**
I've updated the data to reflect the current state of things regarding the support for Chart.js v4.

I've also replaced table columns that were inconsistently placed on the right with a reasonably narrow column on the left with badges.

Hope everyone would like the changes — you can [preview them here](https://github.com/igorlukanin/awesome/blob/update-to-v4/README.md) 😄 

(Obviously, this PR should be squash-merged.)

Cc @simonbrunel @etimberg @LeeLenaleee @kurkle

### CODE REVIEW

**Review by etimberg — DISMISSED** [review]
Reviewed by looking at the rendered markdown from GH. It looks good to me

**Comment by simonbrunel** [comment]
It's very hard to read the version number but also differentiating the yellow and green background (at least for me and probably some colorblind). So while it looks nicer, I find it harder to read than the current master. Also, I'm a bit concerned by the length of the first column (all the shell-io links), making it also harder to maintain I guess.

An alternative would be to use emojis instead:

````
Support | Name | Description
------- | ---- | ----------
2️⃣ 3️⃣    | foo  | bar
````

Renders to:

Support | Name | Description
-------- | ------ | -----------
2️⃣ 3️⃣      | foo      | bar

Not sure there is different colors though but I feel it's a bit easier to read the number and much compact in it's raw form.

Thoughts?

**Comment by igorlukanin** [comment]
@simonbrunel Thanks for amazing feedback!

I _love_ the solution with emoji, didn't actually think about that. Very clever.

The only disadvantage of emojis that I see is that they all look kind of the same because they are on the same background—one has to actually read the number. I tried to employ the color coding with the yellow-green-brightgreen range.

Anyhow, let me update the PR to emojis.

**Comment by igorlukanin** [comment]
@simonbrunel @etimberg Updated! WDYT?

**Comment by simonbrunel** [comment]
Thanks @igorlukanin. 

Another (good/bad?) idea to make it more readable: add a "blank" emojis for unsupported versions so all version are (almost) vertically aligned, thus easier to process.

Support | Name | Description
------- | ---- | ----------
2️⃣ 3️⃣ 4️⃣ | foo  | bar
・ 3️⃣ 4️⃣ | foo  | bar 
2️⃣ ・ ・ | foo  | bar
・ ・ 4️⃣ | foo  | bar

**Comment by igorlukanin** [comment]
@simonbrunel Wow, that is great suggestion. On my machine, ❕ (white exclamation mark) has the same width like the numbers. With it, all versions are perfectly aligned. WDYT? (IDK if that would be ugly in dark mode.)

I've [updated](https://github.com/igorlukanin/awesome/blob/update-to-v4/README.md) the PR.

**Review by kurkle — DISMISSED** [review]
Looks pretty good on mobile too.
image

**Review by LeeLenaleee — DISMISSED** [review]
Minor thing might be an idea to also specify the ! Means not supported version at the part where you describe the versions

**Comment by igorlukanin** [comment]
@LeeLenaleee Makes sense. Clarified that.

**Review by LeeLenaleee — DISMISSED** [review]

**Review by etimberg — DISMISSED** [review]

**Comment by simonbrunel** [comment]
I'm not super fan of the ❕(I prefer something less visible ・) but everyone else seem OK, so let's keep it :)

If ❕ means "not supported", then for consistency it needs to be set for all versions:

Support | Name | Description
------- | ---- | ----------
2️⃣ 3️⃣ 4️⃣ | foo  | bar
❕ 3️⃣ 4️⃣ | foo  | bar 
2️⃣ ❕ ❕ | foo  | bar
❕ ❕ 4️⃣ | foo  | bar

**Comment by igorlukanin** [comment]
Updated everything for consistency! 😄

**Review by etimberg — APPROVED** [review]

**Review by kurkle — APPROVED** [review]
Some v4 support is already outdated,  but those can be updated in later commits by the owners.

**Review by simonbrunel — APPROVED** [review]

**Comment by simonbrunel** [comment]
Thanks @igorlukanin ❕

**Pull request merged**
