### PR TITLE
Add dayjs adapter (<4KB gzipped bundle size)

### PR DESCRIPTION
**Pull request by amerkay**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

Added [dayjs](https://github.com/bolstycjw/chartjs-adapter-dayjs-4), dayjs adapter (<4KB gzipped). Not my lib, I simply needed it and it works well with a tiny footprint.

All the other options, while they have more features, add way too much to the bundle size for simply needing a time x-axis. dayjs is the solution.

### CODE REVIEW

**Review by stockiNail — COMMENTED** [review]
The extensions should be in alphabetic order therefore it should be after date-fns
Not clear why gzipped info has been added. In my opinion no needed.

**Comment by amerkay** [comment]
I'll fix the order.

The size gzipped is the main criteria for a frontend developer. Moment can add up to 400kb parsed 100kb gzipped. The other libs are just too much for simply using the time x axis.

**Comment by stockiNail** [comment]
> The size gzipped is the main criteria for a frontend developer. Moment can add up to 400kb parsed 100kb gzipped. The other libs are just too much for simply using the time x axis.

This awesome project (but the maintainers can correct me if I'm wrong) doesn't have the goal to highlight which is the best. It's mapping the ecosystem around Chart.js.
Whoever will use this adapter or Moment or Luxon or what ever, could evaluate which is the "best", based on own use cases.

**Comment by benmccann** [comment]
I'd probably leave out the gzip info though because it depends on options. E.g. dayjs size grows as you add languages you support whereas Luxon doesn't. There are also other attributes you can compare date libraries on and we don't list those details. I can't wait for `tc39/proposal-temporal` so that we don't need any of these adapters anymore

**Comment by amerkay** [comment]
Done. Removed gzip sizes and it's now alphabetically listed.

**Review by kurkle — APPROVED** [review]
I would suggest removing the dayjs version (4) from the package name, but its up to you.

**Review by etimberg — APPROVED** [review]

**Review by benmccann — APPROVED** [review]
agree on removing the version number from the package name so you don't need to create a new package for every version, but also agree it's up to you

**Comment by amerkay** [comment]
> I would suggest removing the dayjs version (4) from the package name, but its up to you.

It's not my lib. I just needed something that won't add much to the bundle ;)

**Pull request merged**
