### PR TITLE
add chartjs-scale-hierarchical

### PR DESCRIPTION
**Pull request by sgratzl**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

adds a link to the https://github.com/datavisyn/chartjs-scale-hierarchical plugin which allows to have a hierarchical categorical scale that can be collapsed, expanded, and focused on a specific level. 

hierarchy

### CODE REVIEW

**Review by benmccann — APPROVED** [review]

**Review by simonbrunel — CHANGES_REQUESTED** [review]
Hi @sgratzl, thank you for your submission.

I checked your plugin and it doesn't seem to follow [our guidelines](https://www.chartjs.org/docs/latest/developers/plugins.html#plugin-id):
- the name of the package should be: `chartjs-plugin-hierarchical`
- the [name of the plugin](https://github.com/datavisyn/chartjs-scale-hierarchical/blob/master/src/plugin/hierarchical.js#L54) should be: `id: 'hierarchical'`

Can you please address these issues?

**Comment by SeppPenner** [comment]
I have created a pull request for this under https://github.com/datavisyn/chartjs-scale-hierarchical/pull/21.

**Comment by sgratzl** [comment]
re repo name to `chartjs-plugin-hierarchical`:

In the end this plugin main contribution to Chart.js is another scale type (`hierarchical`). The plugin part is just to support this new scale type. Thus, it is similar to extending Chart.js with another chart type but for a new scale. That's why I named the plugin `chartjs-scale-hierarchical`. However, if you insist I rename the repo to the suggested one

**Comment by sgratzl** [comment]
closing in favor of the upcoming new one

**Pull request closed without merging**
