### PR TITLE
Add link to chartjs-chart-geo

### PR DESCRIPTION
**Pull request by sgratzl**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

Hi I know that I'm too early, but I wanted to share this plugin with you, cause I think it is very neat and useful to extend chart.js and open it to another data domain.

This PR will add a link to https://github.com/sgratzl/chartjs-chart-geo which allows to render maps in chart.js. Adds two new chart types: choropleth and bubbleMap.

Choropleth

Earth Choropleth

Bubble Map

Interactive Examples
 * [Choropleth](https://codepen.io/sgratzl/pen/GRKLQBw)
 * [Earth Choropleth](https://codepen.io/sgratzl/pen/qBWwxKP)
 * [Bubble Map](https://codepen.io/sgratzl/pen/wvwZyxb)

### CODE REVIEW

**Comment by benmccann** [comment]
Wow! This is amazing!

**Comment by etimberg** [comment]
This looks great. @sgratzl is this ready to review

**Comment by sgratzl** [comment]
> This looks great. @sgratzl is this ready to review

according to your contribution guidelines the plugin has to exist for more than 30 days. So, far it is just two weeks old even tho I'm done and it is published.

**Comment by sgratzl** [comment]
enough time has passed since this plugin was created. So, it can be merged whenever you have time

**Review by kurkle — APPROVED** [review]

**Review by etimberg — APPROVED** [review]

**Pull request merged**
