### PR TITLE
Add link to chartjs-chart-graph

### PR DESCRIPTION
**Pull request by sgratzl**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

Hi I know that I'm too early, but I wanted to share this plugin with you, cause I think it is very neat and useful to extend chart.js and open it to another data domain.

This PR will add a link to https://github.com/sgratzl/chartjs-chart-graph which allows to render graphs and trees. Adds four new chart types: `graph`, `forceDirectedGraph`, `dendogram`, and `tree`. 

force

dend_h

tree_v

radial

Works also great with https://github.com/chartjs/chartjs-plugin-datalabels or https://github.com/chrispahm/chartjs-plugin-dragdata

data label

Interactive Examples
 * [Force Directed Layout](https://codepen.io/sgratzl/pen/bGbzREq)
 * [Tree Layouts](https://codepen.io/sgratzl/pen/wvwNeWg)
 * [Tree With Data Labels](https://codepen.io/sgratzl/pen/XWrOgpy)

### CODE REVIEW

**Comment by etimberg** [comment]
Same question, is this ready to review?

**Comment by sgratzl** [comment]
same here :-)

> enough time has passed since this plugin was created. So, it can be merged whenever you have time

**Review by kurkle — DISMISSED** [review]

**Review by etimberg — DISMISSED** [review]

**Comment by etimberg** [comment]
This need a rebase, then I will merge

**Comment by sgratzl** [comment]
please squeeze and merge to avoid superfluous commits. thx

**Review by etimberg — APPROVED** [review]

**Comment by sgratzl** [comment]
ping

**Review by kurkle — APPROVED** [review]

**Pull request merged**
