### PR TITLE
Add symfony UX integration

### PR DESCRIPTION
**Pull request by cedriclombardot**
Awesome Contribution Checklist:

- [ ] I have read, and re-read the [Contributing Guidelines](https://github.com/chartjs/awesome/blob/master/CONTRIBUTING.md)
- [ ] I have searched to ensure the suggested item doesn't exist on this list
- [ ] This PR contains only one item

### CODE REVIEW

**Comment by LeeLenaleee** [comment]
You marked the wrapper as only working with V3 while your documentstion suggests it only works with V2:
image

**Comment by simonbrunel** [comment]
@cedriclombardot Please update your PR description with the requested information and check relevant items in the checklist.

**Comment by igorlukanin** [comment]
@cedriclombardot Ping! Since [Chart.js v4](https://github.com/chartjs/Chart.js/releases) was released since you've opened this PR, please check that symfony UX integration actually works woth Chart.js v3 **and v4**. Thanks!

@simonbrunel I think we can probably close this PR in a few days/weeks if no response.

**Comment by simonbrunel** [comment]
@igorlukanin agreed

**Pull request closed without merging**
